version: "3.9"
networks:
  app_network:
    driver: bridge


services:


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app_network
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app_network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
      - redis
    networks:
      - app_network

  