version: "v.2.31.0-desktop.2"
services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: "redis:alpine"
